version: '3.9'
services:
  nginx-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:rw
    networks:
      - gateway-net
networks:
  app-network:
    driver: bridge
  gateway-net:
    external: true
